name = "phone"
main = "./build/index.js"
workers_dev = true
compatibility_date = "2022-11-30"

[build]
command = "npm run build"

[vars]
DISCORD_ID = "1123989427916636292"
DISCORD_PUBLIC_KEY = "130791256841129a40f99b013831211707ced13730bb4469dce876383c8f54c8"
DISCORD_TOKEN = "https://discord.com/api/oauth2/authorize?client_id=1123989427916636292&permissions=8&scope=bot"
TWILIO_ACCOUNT_SID = "AC81d06ce360e9854c4cd8b08c78bd3072"
TWILIO_AUTH_TOKEN = "8184b00b1280523640b6acf028b9af1e"
TWILIO_PHONE_NUMBER =  "12405404043"
MY_PHONE_NUMBER = "919640440407"

FALLBACK_URL = "https://github.com/biaw/phone" # Fallback URL for when a user types the worker address
